### ISSUE TITLE
RG99 vertical blurry line

### ISSUE THREAD

**Issue by NelEctric** [OpenDingux/buildroot#101]
Hi everyone,

I'm in doubt if this can be a related problem with the video driver or vsync on the RG99, can somebody confirm if it appears also on your devices using this OD build?

![screen](https://user-images.githubusercontent.com/75365640/204080811-9337231b-96d1-4d1a-ab6d-33979fc6d504.jpg)

Maybe it's only related a faulty lcd?

Thanks

**Comment by pcercuei** [comment]
Looks like a hardware issue to me.

**Comment by NelEctric** [comment]
Yes, after several checkings it seems to be a hardware fault. Please close this issue. Thanks.
