### ISSUE TITLE
Current build failing with make: *** [Makefile:82: _all] Error 2

### ISSUE THREAD

**Issue by john-parton** [OpenDingux/buildroot#139]
Current HEAD 9e5f8f1c44414b7e6f0c5da3f64e6d133ed447dc fails with cryptic error

`make: *** [Makefile:82: _all] Error 2`

I tried to build with `CONFIG=gcw0 ./rebuild.sh`

Here's the error in "Actions": https://github.com/OpenDingux/buildroot/actions/runs/5868255823/job/15910665877#step:8:1998

Here are the output of stderr and stdout on my machine, Ubuntu 23.04

[build_stderr.log.gz](https://github.com/OpenDingux/buildroot/files/12431452/build_stderr.log.gz)
[build_stdoutt.log.gz](https://github.com/OpenDingux/buildroot/files/12431453/build_stdoutt.log.gz)

**Comment by pcercuei** [comment]
Closing this issue. I'm not sure what was the problem (didn't look at the build log) but everything seems to build fine now.
