### ISSUE TITLE
can't complete installation with latest build

### ISSUE THREAD

**Issue by Rumtrinker** [OpenDingux/buildroot#141]
tried both installations on my retromini with the latest build ( 18-6-2023) . has an error. will try a earlier one i think. 
![20230909_150314](https://github.com/OpenDingux/buildroot/assets/144526106/2f57acc0-f186-4682-8931-9db2ff02f8ca)
![20230909_150501](https://github.com/OpenDingux/buildroot/assets/144526106/b18ae376-f77e-4b21-9624-518dc9a88d04)

**Comment by Rumtrinker** [comment]
retried like 4 times. got installed by some miracle. a lot of thanks.

**Comment by pcercuei** [comment]
Looks like a USB issue, I'd have advised to try with a different cable and/or on a different computer. Good that you got it to flash eventually.

**Comment by Rumtrinker** [comment]
got it working after returning everything to the previous driver. also I
only got working RetroArch ( the only emulador needed) and Commander. other
apps doesnt work on the newest build. Thank you for your hard work.
