### ISSUE TITLE
opendingux: rg350m: Visual artifacts

### ISSUE THREAD

**Issue by jezze** [OpenDingux/buildroot#20]
When switching between applications we get visual artifacts.

This is likely caused by problems in the panel driver.

drivers/gpu/drm/panel/panel-newvision-nv3052c.c

Docs: http://www.phoenixdisplay.com/wp-content/uploads/2019/05/NV3052C-Datasheet-V0.2.pdf

**Comment by citral23** [comment]
Pull request created for fix proposal

**Comment by glebm** [comment]
I see the commit here but where's the pull request? https://github.com/citral23/linux/commit/214636b87607b1e4648198076c1d52617cc5cd31

**Comment by glebm** [comment]
Ah, I see https://github.com/citral23/linux/pull/1

I think you created a pull request into your own fork by accident

**Comment by citral23** [comment]
Sorry I'm new to this, should be ok now.
