### ISSUE TITLE
opendingux: sdl2: apps using sdl2 does not work

### ISSUE THREAD

**Issue by jezze** [OpenDingux/buildroot#23]
SDL2 just renders a black screen.

Normally in SDL2 you would create a renderer with:

>  SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);

And this would give you opengles2, however opengles2 does not seem to work.

You can force opengles instead, simply by setting driver index to 1 like this:

>  SDL_CreateRenderer(window, 1, SDL_RENDERER_ACCELERATED);

This works as a workaround but should be fixed.

These are the available driver indices:

Driver 0: opengles2
Driver 1: opengles
Driver 2: software

Secondly, I've noticed there are some frame dropping happening which seems to be related to vsync. You can workaround that problem by running:

> SDL_GL_SetSwapInterval(1);

This should have the same effect (but I have not tried it):

>  SDL_CreateRenderer(window, 1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

**Comment by jezze** [comment]
Here is the little working testprogram I did. Build instructions found in readme.

https://github.com/jezze/testsdl2

**Comment by jezze** [comment]
I have now checked what the drivers are:

Driver 0: opengles2
Driver 1: opengles
Driver 2: software

So this tells me opengles works, and opengles2 does not.

**Comment by jezze** [comment]
There are also framedrops going on. Seems to be a related to vsync. Adding SDL_GL_SetSwapInterval(1) fixes that problem.

**Comment by KatyushaScarlet** [comment]
Same issue with rg350m, using 640x480 resolution.
The screen just turn black and the device is stuck.

**Comment by pcercuei** [comment]
It should work out-of-the-box now; please test. Use `-1` as the render driver so that it's picked automatically.

**Comment by jezze** [comment]
Yes this works now. Tried on my RG350M. Nice work!
