### ISSUE TITLE
opendingux: Bad Address error in shell

### ISSUE THREAD

**Issue by jezze** [OpenDingux/buildroot#33]
Sometimes I can get a Bad Address error in sh after a bit of use. When this happens there is nothing I can do but reboot. I heard this is a known issue without a solution.

**Comment by uncletrunks** [comment]
I can confirm that this is happening to me as well. I've noticed it while running from an OPK as well on occasion. Not sure what could be causing it to be honest.

**Comment by jezze** [comment]
I don't know what changed but I couldn't reproduce this and it used to be fairly easy to trigger earlier. I guess we can consider it fixed. Will close for now.
