### ISSUE TITLE
Trail on OD logo on the RG350M

### ISSUE THREAD

**Issue by fgl82** [OpenDingux/buildroot#50]
This is filmed in slow motion

https://user-images.githubusercontent.com/6005916/110680136-fe92da00-81b6-11eb-9046-65b7a7c9f88d.mp4

**Comment by jezze** [comment]
I see no one had replied. Yes we are aware of this.  It has something to do with the panel driver and we thought we had fixed it but it is still there.

**Comment by fgl82** [comment]
Thanks, let me know if you need any specifics about my device, as I think I've seen mentioned only some screens do it

**Comment by littlehui** [comment]
My RG350M has the same problem too

**Comment by Tartopoireaux** [comment]
Same things on my 2 RG350M

**Comment by pcercuei** [comment]
Closing now as it's been fixed.
