### ISSUE TITLE
"Updated rootfs is corrupted!"

### ISSUE THREAD

**Issue by SerbianLastName** [OpenDingux/buildroot#56]
Every time I try to run the updated I get an "Updated rootfs is corrupted! Please report this bug"
It also looks like it says "Segmentation error" in the terminal before the error screen pops up.
Getting this on an RG-350M, have tried numerous times on freshly flashed firmware, and always the same result, have tried different SD cards, different versions of the updater, flashing new stock firmware with and without extending the ext4 partition, always the same error.

**Comment by askotx** [comment]
I can confirm this issue too

**Comment by pcercuei** [comment]
The installer copies the files then verifies that they were copied correctly, if you get this error, that probably means that the native firmware is corrupting the files.

If you run Linux, you can try flashing OD nightly over USB from the terminal using the odboot-client tool: https://app.box.com/s/qxz0n633wibai6yxbxqy3mn4ay7j2d3l
