### ISSUE TITLE
opendingux: Build SDL_Image with LBM support

### ISSUE THREAD

**Issue by uncletrunks** [OpenDingux/buildroot#66]
I had someone contact me through discord about my port of openxcom not working with Terror From the Deep. The problem seems to come down to the flags that SDL_image is being compiled with for OD. Terror From the Deep requires support for LBM images, which the OD build of SDL_image does not currently have.

Currently, these flags are set in `configs/od_gcw0_defconfig` to enable different SDL_image features:

```
BR2_PACKAGE_SDL_IMAGE_GIF=y
BR2_PACKAGE_SDL_IMAGE_PCX=y
BR2_PACKAGE_SDL_IMAGE_TARGA=y
BR2_PACKAGE_SDL_IMAGE_XPM=y
```

I would like to see `BR2_PACKAGE_SDL_IMAGE_LBM=y` added to this if possible.

**Comment by pcercuei** [comment]
Enabled in https://github.com/OpenDingux/buildroot/commit/96f5259dfcd148ecf527f586b58cff24a18e7b71
