### ISSUE TITLE
Cannot install update from stock firmware

### ISSUE THREAD

**Issue by gibb3h** [OpenDingux/buildroot#76]
Hello, I am trying to install the latest version on my RG280v from stock firmware (Kernal version: 3.12.0-dingux+ Root file system version: ge757a1a) but when running the OS Update I see an "input/output error" flash up in the terminal and then the updater gives me a "Failed to update rootfs! Do you have enough space available?" error

I am using a 16gb SD card, flashed using balena which I believe gives me a 4gb system partition correct? does this partition need to be enlarged some how?  If so could you advise on how to do this within windows?

Thanks
Gib

**Comment by gibb3h** [comment]
After several more tries, I am now occasionally getting through to the verifying fs stage, at which point I get a popup saying that "Updated rootfs is corrupted! Please report this bug!"

consider it reported I guess? ^_^

**Comment by pcercuei** [comment]
@gibb3h sorry for the late reply, looks like I don't get emails when new bugs are reported.

If you get a "input/output error" when trying to update from the stock firmware, that means that your stock firmware is in a bad shape - probably corrupted. So the "updated rootfs is corrupted" error looks genuine. Try to reflash your stock firmware first. If it keeps happening after a reflash, consider using a different SD card.
