### ISSUE TITLE
Move buildroot to a submodule

### ISSUE THREAD

**Issue by glebm** [OpenDingux/buildroot#90]
OpenDingux buildroot is currently a fork of upstream buildroot, making merges/rebases a bit of work.
It'd be easier to maintain and upgrade if  buildroot was in a submodule pointing to upstream, or to our own fork of upstream buildroot with minimal differences

Some examples of doing it this way:

1. Batocera: https://github.com/batocera-linux/batocera.linux
2. RetroLX: https://github.com/RetroLX/retrolx

**Comment by pcercuei** [comment]
I don't see the point. I have zero problems merging upstream Buildroot changes with the current system.

**Comment by glebm** [comment]
In terms of organization, it's nice to have all our custom code cleanly separated, but it's a minor thing

**Comment by pcercuei** [comment]
But it is already cleanly separated - it is in `boards/opendingux/`

**Comment by glebm** [comment]
Almost, `configs/od_*` and `(re)build.sh` are not in `boards/opendingux`
